### ISSUE TITLE
Eveytime the same picture is updated again

### ISSUE THREAD

**Issue by 91DarioDev** [JosXa/BotListBot#1]
https://github.com/JosXa/BotListBot/blob/fb51363465a09377aa30bbad0f2f2f2a257dc7ef/util.py#L64

Instead of updating the same picture again everytime, you may do this: when the bot starts it sends the picture somewhere on telegram and the returned file id can be associated to a variable. Now you use the variable and you don’t have to update the same file again and again

**Comment by JosXa** [comment]
There are more important bottlenecks, this is just the non-admin troll *shrug*
