### ISSUE TITLE
Wrong Reply when using hints

### ISSUE THREAD

**Issue by FabianPastor** [JosXa/BotListBot#14]
In: https://github.com/JosXa/BotListBot/blob/a036beee9a842c2f979a18bb1ee9c1dc31742810/botlistbot/components/botlistchat.py#L231

if reply_to is set it should use the User from update.message.reply_to_message and not the user that asked for sending the hint to another user.

**Comment by JosXa** [comment]
@FabianPastor That's what it does 🤨
https://github.com/JosXa/BotListBot/blob/a036beee9a842c2f979a18bb1ee9c1dc31742810/botlistbot/components/botlistchat.py#L223

**Comment by AndrewLaneX** [comment]
@JosXa I think you misunderstood this
![image](https://user-images.githubusercontent.com/32808683/98885453-0ab49800-2460-11eb-94e4-89331ec48f2a.png)

**Comment by JosXa** [comment]
We had a lengthy discussion in the group :)
